### ISSUE TITLE
Make What's Different About Manage Responsive

### ISSUE THREAD

**Issue by jaison080** [jaison080/tailwind-practice#2]

**Comment by gani2267** [comment]
can you please give more info about this issue

**Comment by gani2267** [comment]
![WhatsApp Image 2022-10-10 at 3 03 40 AM](https://user-images.githubusercontent.com/84265879/194780486-1d0f709b-3e55-46bc-9b1b-e7999a7431bd.jpeg)

Here we can see that these circular images are not properly positioning in responsive design 
Please assign this issue to me I want to work on it

**Comment by jaison080** [comment]
Yeah sure
